export const ADD_BOOK = "BOOK/ADD_BOOK";
export const UPDATE_BOOK_STATE = "BOOK/UPDATE_STATE";
export const SAGA_DELETE_BOOK = "BOOK/SAGA_DELETE_BOOK";
export const SAGA_FILTER_BOOK = "BOOK/SAGA_FILTER_BOOK";
export const SAGA_REMOVE_FILTER_BOOK = "BOOK/SAGA_REMOVE_FILTER_BOOK";