export const ADD_WRITER = "WRITER/ADD_WRITER";
export const UPDATE_WRITER_STATE = "WRITER/UPDATE_STATE";
export const SAGA_DELETE_WRITER = "WRITER/SAGA_DELETE_WRITER";
export const SAGA_FILTER_WRITER = "WRITER/SAGA_FILTER_WRITER";
export const SAGA_REMOVE_FILTER_WRITER = "WRITER/SAGA_REMOVE_FILTER_WRITER";
export const SAGA_EDIT_WRITER = "WRITER/SAGA_EDIT_WRITER";